# Generated by Django 4.1 on 2022-11-27 07:54

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(db_column='course_id', primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=100, unique=True)),
                ('course_abbr', models.CharField(blank=True, db_column='course_abbr', default='', max_length=20)),
                ('course_credit', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(db_column='dept_id', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('section_name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=50)),
                ('unit', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=50)),
                ('middle_name', models.CharField(blank=True, max_length=50)),
                ('last_name', models.CharField(default='', max_length=50)),
                ('home_address', models.CharField(default='', max_length=150)),
                ('landline_no', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region='PH')),
                ('cellphone_no', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region='PH')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('student_classification', models.PositiveIntegerField(choices=[(1, 'New'), (2, 'Continuing'), (3, 'Transferee'), (4, 'Returnee'), (5, 'Cross Enrollee'), (6, 'Shiftee From')], default=1)),
                ('registration_status', models.PositiveIntegerField(choices=[(1, 'Regular'), (2, 'Irregular'), (3, 'Temporary')], default=1)),
                ('shiftee_from', models.CharField(blank=True, max_length=150)),
                ('birthday', models.DateField(default=django.utils.timezone.now)),
                ('birthplace', models.CharField(default='', max_length=150)),
                ('age', models.PositiveIntegerField(default=18, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(12)])),
                ('sex', models.PositiveIntegerField(choices=[(1, 'Male'), (2, 'Female')], default=1)),
                ('religion', models.CharField(blank=True, default='', max_length=50)),
                ('nationality', models.CharField(blank=True, default='', max_length=50)),
                ('civil_status', models.CharField(blank=True, default='', max_length=50)),
                ('school_elementary', models.CharField(blank=True, default='', max_length=150)),
                ('school_year_elemetary', models.PositiveIntegerField(blank=True, default=2022, validators=[django.core.validators.MaxValueValidator(3000), django.core.validators.MinValueValidator(1985)])),
                ('school_access_elementary', models.PositiveIntegerField(choices=[(1, 'Private'), (2, 'Public')], default=1)),
                ('school_address_elementary', models.CharField(blank=True, default='', max_length=150)),
                ('school_high', models.CharField(blank=True, default='', max_length=150)),
                ('school_year_high', models.PositiveIntegerField(blank=True, default=2022, validators=[django.core.validators.MaxValueValidator(3000), django.core.validators.MinValueValidator(1985)])),
                ('school_access_high', models.PositiveIntegerField(choices=[(1, 'Private'), (2, 'Public')], default=1)),
                ('school_address_high', models.CharField(blank=True, default='', max_length=150)),
                ('school_last_attended', models.CharField(blank=True, default='', max_length=150)),
                ('school_last_attended_address', models.CharField(blank=True, default='', max_length=150)),
                ('parent_guardian', models.CharField(blank=True, default='', max_length=50)),
                ('parent_address', models.CharField(blank=True, default='', max_length=150)),
                ('parent_occupation', models.CharField(blank=True, default='', max_length=50)),
                ('parent_landline_no', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region='PH')),
                ('parent_cellphone_no', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region='PH')),
                ('year_level', models.PositiveIntegerField(choices=[(1, '1st'), (2, '2nd'), (3, '3rd'), (4, '4th')], default=1)),
                ('school_year', models.PositiveIntegerField(default=2022, validators=[django.core.validators.MaxValueValidator(3000), django.core.validators.MinValueValidator(2000)])),
                ('semester', models.PositiveIntegerField(choices=[(1, 1), (2, 2)], default=1)),
                ('approved', models.BooleanField(default=False)),
                ('form_137', models.FileField(blank=True, upload_to='documents/')),
                ('card_138', models.FileField(blank=True, upload_to='documents/')),
                ('goodmoral', models.FileField(blank=True, upload_to='documents/')),
                ('medical_clearance', models.FileField(blank=True, upload_to='documents/')),
                ('application_form', models.FileField(blank=True, upload_to='documents/')),
                ('transcript_of_record', models.FileField(blank=True, upload_to='documents/')),
                ('notice_of_admission', models.FileField(blank=True, upload_to='documents/')),
                ('cert_of_transfer', models.FileField(blank=True, upload_to='documents/')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='records.course')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='records.section')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'semester', 'school_year')},
            },
        ),
        migrations.CreateModel(
            name='FormsApproval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_137', models.BooleanField(default=False)),
                ('card_138', models.BooleanField(default=False)),
                ('goodmoral', models.BooleanField(default=False)),
                ('medical_clearance', models.BooleanField(default=False)),
                ('application_form', models.BooleanField(default=False)),
                ('transcript_of_record', models.BooleanField(default=False)),
                ('notice_of_admission', models.BooleanField(default=False)),
                ('cert_of_transfer', models.BooleanField(default=False)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.record')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='course_department',
            field=models.ForeignKey(db_column='course_department_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='records.department'),
        ),
        migrations.AddField(
            model_name='course',
            name='subjects',
            field=models.ManyToManyField(blank=True, to='records.subject'),
        ),
    ]
