# Generated by Django 4.1 on 2022-11-27 14:11

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='record',
            unique_together={('user', 'semester', 'year_level', 'school_year')},
        ),
    ]
