# Generated by Django 4.1 on 2022-11-24 15:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_alter_record_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='year_level',
            field=models.PositiveIntegerField(choices=[('1st', 1), ('2nd', 2), ('3rd', 3), ('4th', 4)], default=1),
        ),
        migrations.AlterField(
            model_name='record',
            name='birthday',
            field=models.DateField(default=datetime.datetime(2022, 11, 24, 23, 34, 26, 746234)),
        ),
    ]
