# Generated by Django 4.1 on 2022-12-01 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_alter_record_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='registration_status',
            field=models.PositiveIntegerField(choices=[(1, 'Regular'), (2, 'Irregular')], default=1),
        ),
    ]
