# Generated by Django 4.1 on 2022-09-18 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_remove_record_father_contact_remove_record_hsc_board_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='semester',
            field=models.PositiveIntegerField(choices=[('1', 1), ('2', 2), ('3', 3), ('4', 4)], default=1),
        ),
    ]
