# Generated by Django 4.1 on 2023-01-09 16:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_alter_record_registration_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='school_year',
            field=models.PositiveIntegerField(default=2023, validators=[django.core.validators.MaxValueValidator(3000), django.core.validators.MinValueValidator(2000)]),
        ),
        migrations.AlterField(
            model_name='record',
            name='school_year_elemetary',
            field=models.PositiveIntegerField(blank=True, default=2023, validators=[django.core.validators.MaxValueValidator(3000), django.core.validators.MinValueValidator(1985)]),
        ),
        migrations.AlterField(
            model_name='record',
            name='school_year_high',
            field=models.PositiveIntegerField(blank=True, default=2023, validators=[django.core.validators.MaxValueValidator(3000), django.core.validators.MinValueValidator(1985)]),
        ),
    ]
