# Generated by Django 4.1 on 2022-09-18 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_record_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
