# Generated by Django 4.1 on 2022-10-08 02:49

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0004_record_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='home_address',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='record',
            name='landline_no',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None),
        ),
        migrations.AlterField(
            model_name='record',
            name='semester',
            field=models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)], default=1),
        ),
    ]
