# Generated by Django 4.1 on 2022-10-08 03:39

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0005_record_home_address_record_landline_no_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(db_column='dept_id', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('section_name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=50)),
                ('unit', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='record',
            name='cellphone_no',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None),
        ),
        migrations.AddField(
            model_name='record',
            name='email',
            field=models.EmailField(blank=True, max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='record',
            name='shiftee_from',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='record',
            name='student_classification',
            field=models.PositiveIntegerField(choices=[(1, 'New'), (2, 'Continuing'), (3, 'Transferee'), (4, 'Returnee'), (5, 'Cross Enrollee'), (6, 'Shiftee From')], default=1, max_length=1),
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(db_column='course_id', primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=100, unique=True)),
                ('course_abbr', models.CharField(blank=True, db_column='course_abbr', default='', max_length=20)),
                ('course_credit', models.PositiveSmallIntegerField()),
                ('course_department', models.ForeignKey(db_column='course_department_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='records.department')),
                ('subjects', models.ManyToManyField(to='records.subject')),
            ],
        ),
        migrations.AddField(
            model_name='record',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='records.course'),
        ),
        migrations.AddField(
            model_name='record',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='records.section'),
        ),
    ]
