# Generated by Django 4.1 on 2022-10-08 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0006_department_section_subject_record_cellphone_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
