# Generated by Django 4.1 on 2022-10-08 04:07

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0007_alter_record_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='age',
            field=models.PositiveIntegerField(default=18, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(12)]),
        ),
        migrations.AddField(
            model_name='record',
            name='birthday',
            field=models.DateField(default=datetime.datetime(2022, 10, 8, 12, 7, 43, 365218)),
        ),
        migrations.AddField(
            model_name='record',
            name='birthplace',
            field=models.CharField(default='', max_length=150),
        ),
    ]
