# Generated by Django 4.1 on 2022-10-14 13:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0008_record_age_record_birthday_record_birthplace'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='birthday',
            field=models.DateField(default=datetime.datetime(2022, 10, 14, 21, 30, 5, 416180)),
        ),
    ]
