# Generated by Django 4.1 on 2022-10-20 12:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0009_alter_record_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='registration_status',
            field=models.PositiveIntegerField(choices=[(1, 'Regular'), (2, 'Irregular'), (3, 'Temporary')], default=1, max_length=1),
        ),
        migrations.AlterField(
            model_name='record',
            name='birthday',
            field=models.DateField(default=datetime.datetime(2022, 10, 20, 20, 36, 52, 748822)),
        ),
    ]
