# Generated by Django 4.1 on 2022-10-20 14:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0011_record_civil_status_record_nationality_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='birthday',
            field=models.DateField(default=datetime.datetime(2022, 10, 20, 22, 12, 10, 878179)),
        ),
    ]
