# Generated by Django 4.1 on 2022-10-22 00:36

import datetime
import django.core.validators
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0012_alter_record_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='parent_address',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='record',
            name='parent_cellphone_no',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None),
        ),
        migrations.AddField(
            model_name='record',
            name='parent_guardian',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='record',
            name='parent_landline_no',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None),
        ),
        migrations.AddField(
            model_name='record',
            name='parent_occupation',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='record',
            name='school_access_elementary',
            field=models.PositiveIntegerField(choices=[(1, 'Private'), (2, 'Public')], default=1, max_length=1),
        ),
        migrations.AddField(
            model_name='record',
            name='school_access_high',
            field=models.PositiveIntegerField(choices=[(1, 'Private'), (2, 'Public')], default=1, max_length=1),
        ),
        migrations.AddField(
            model_name='record',
            name='school_address_elementary',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='record',
            name='school_address_high',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='record',
            name='school_high',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='record',
            name='school_last_attended',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='record',
            name='school_last_attended_address',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='record',
            name='school_year',
            field=models.PositiveIntegerField(blank=True, default=2022, validators=[django.core.validators.MaxValueValidator(3000), django.core.validators.MinValueValidator(2000)]),
        ),
        migrations.AddField(
            model_name='record',
            name='school_year_elemetary',
            field=models.PositiveIntegerField(blank=True, default=2022, validators=[django.core.validators.MaxValueValidator(3000), django.core.validators.MinValueValidator(1985)]),
        ),
        migrations.AddField(
            model_name='record',
            name='school_year_high',
            field=models.PositiveIntegerField(blank=True, default=2022, validators=[django.core.validators.MaxValueValidator(3000), django.core.validators.MinValueValidator(1985)]),
        ),
        migrations.AlterField(
            model_name='record',
            name='birthday',
            field=models.DateField(default=datetime.datetime(2022, 10, 22, 8, 36, 35, 532189)),
        ),
        migrations.AlterField(
            model_name='record',
            name='school_elementary',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
