# Generated by Django 4.1 on 2022-10-22 06:04

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('records', '0013_record_parent_address_record_parent_cellphone_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='birthday',
            field=models.DateField(default=datetime.datetime(2022, 10, 22, 14, 4, 41, 378379)),
        ),
        migrations.AlterField(
            model_name='record',
            name='school_year',
            field=models.PositiveIntegerField(default=2022, validators=[django.core.validators.MaxValueValidator(3000), django.core.validators.MinValueValidator(2000)]),
        ),
        migrations.RemoveField(
            model_name='record',
            name='user',
        ),
        migrations.AddField(
            model_name='record',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
