# Generated by Django 4.1 on 2022-11-01 10:18

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0017_record_application_form_record_card_138_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormsApproval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_137', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='record',
            name='birthday',
            field=models.DateField(default=datetime.datetime(2022, 11, 1, 18, 18, 37, 611604)),
        ),
        migrations.AddField(
            model_name='record',
            name='forms_approval',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='records.formsapproval'),
        ),
    ]
