# Generated by Django 4.1 on 2022-11-01 13:55

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0019_alter_record_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='formsapproval',
            name='application_form',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='formsapproval',
            name='card_138',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='formsapproval',
            name='cert_of_transfer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='formsapproval',
            name='goodmoral',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='formsapproval',
            name='medical_clearance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='formsapproval',
            name='notice_of_admission',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='formsapproval',
            name='transcript_of_record',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='record',
            name='birthday',
            field=models.DateField(default=datetime.datetime(2022, 11, 1, 21, 55, 19, 998712)),
        ),
        migrations.AlterField(
            model_name='record',
            name='forms_approval',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='records.formsapproval'),
        ),
    ]
