# Generated by Django 4.1 on 2022-11-08 16:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0020_formsapproval_application_form_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='birthday',
            field=models.DateField(default=datetime.datetime(2022, 11, 9, 0, 46, 42, 520022)),
        ),
    ]
