# Generated by Django 4.1 on 2022-11-09 14:25

import datetime
from django.db import migrations, models
import django.db.models.deletion
import records.models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0021_alter_record_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='birthday',
            field=models.DateField(default=datetime.datetime(2022, 11, 9, 22, 25, 50, 896093)),
        ),
        migrations.AlterField(
            model_name='record',
            name='forms_approval',
            field=models.OneToOneField(default=records.models.FormsApproval.get_new, on_delete=django.db.models.deletion.CASCADE, to='records.formsapproval'),
        ),
        migrations.AlterField(
            model_name='record',
            name='semester',
            field=models.PositiveIntegerField(choices=[(1, 1), (2, 2)], default=1),
        ),
    ]
