# Generated by Django 4.1 on 2022-11-09 15:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0022_alter_record_birthday_alter_record_forms_approval_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='subjects',
            field=models.ManyToManyField(blank=True, to='records.subject'),
        ),
        migrations.AlterField(
            model_name='record',
            name='birthday',
            field=models.DateField(default=datetime.datetime(2022, 11, 9, 23, 11, 25, 699526)),
        ),
    ]
