# Generated by Django 4.1 on 2022-11-09 15:21

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0023_alter_course_subjects_alter_record_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='birthday',
            field=models.DateField(default=datetime.datetime(2022, 11, 9, 23, 21, 39, 736097)),
        ),
        migrations.AlterField(
            model_name='record',
            name='school_year',
            field=models.PositiveIntegerField(default=2022, unique=True, validators=[django.core.validators.MaxValueValidator(3000), django.core.validators.MinValueValidator(2000)]),
        ),
        migrations.AlterUniqueTogether(
            name='record',
            unique_together={('semester', 'school_year')},
        ),
    ]
