# Generated by Django 4.1 on 2022-11-24 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authority', '0002_customuser_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='picture',
            field=models.ImageField(blank=True, default='', null=True, upload_to='images/'),
        ),
    ]
